void    TerraformAverage ();
void    TerraformCoast ();
void    TerraformColors ();
GLrgba  TerraformColorGenerate (SurfaceColor c, float moisture, float temperature, int seed);
void    TerraformClimate ();
void    TerraformFill ();
void    TerraformOceans ();
void    TerraformPrepare ();
void    TerraformRivers (int count);
void    TerraformZones ();
