void Render (void);
void RenderCreate (int width, int height, int bits, bool fullscreen);
void RenderCanvasBegin (int left, int right, int bottom, int top, int size);
void RenderCanvasEnd ();
void RenderClick (int x, int y);
void RenderInit  (void);
void RenderLoadingScreen (float progress);
int  RenderMaxDimension ();
void RenderTexture (unsigned id);
void RenderUpdate (void);
